server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:CitizenDB
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: CITIZEN-SERVICE